### ISSUE TITLE
Misc todo

### ISSUE THREAD

**Issue by simontaylor81** [simontaylor81/Syrup#15]
- [ ] Clear previous script when loading new project
- [x] Open documents when adding to project
- [x] Add multiple files to project at once
- [ ] Save changes prompt when closing document
- [x] Clear output window when re-running script
- [x] Proper output from script tests
- [ ] Remove items from recently opened list if they don't exist
- [ ] Save window layout
- [ ] Save open documents outside of project file
- [ ] Make open document set a service to avoid slightly tangled dependencies?
